### ISSUE TITLE
[CacheAdapter] ERROR An error occurred while watching a resource io.kubernetes.client.ApiException: Forbidden

### ISSUE THREAD

**Issue by rogaha** [nextbreakpoint/flink-k8s-toolbox#43]
Nice job putting this together @nextbreakpoint. I've got the following error while deploying the `operator`: 

```
2020/11/30 17:48:10.609 +0000 [main] [LaunchOperator] INFO  Launching operator...
2020/11/30 17:48:12.222 +0000 [vert.x-eventloop-thread-0] [OperatorVerticle] WARN  HTTPS not enabled!
2020/11/30 17:48:13.010 +0000 [Thread-7] [CacheAdapter] INFO  Watch loop started
2020/11/30 17:48:13.102 +0000 [Thread-9] [CacheAdapter] INFO  Watch loop started
2020/11/30 17:48:13.110 +0000 [Thread-8] [CacheAdapter] INFO  Watch loop started
2020/11/30 17:48:13.206 +0000 [vert.x-eventloop-thread-0] [i.v.c.i.l.c.VertxIsolatedDeployer] INFO  Succeeded in deploying verticle
2020/11/30 17:48:13.206 +0000 [vert.x-eventloop-thread-0] [i.v.c.i.l.c.VertxIsolatedDeployer] INFO  Succeeded in deploying verticle
2020/11/30 17:48:14.704 +0000 [Thread-7] [CacheAdapter] ERROR An error occurred while watching a resource
io.kubernetes.client.ApiException: Forbidden
	at io.kubernetes.client.util.Watch.createWatch(Watch.java:104) ~[flink-k8s-toolbox.jar:1.3.5-beta]
	at com.nextbreakpoint.flinkoperator.server.common.KubeClient.watchFlickClusters(KubeClient.kt:261) ~[flink-k8s-toolbox.jar:1.3.5-beta]
	at com.nextbreakpoint.flinkoperator.server.operator.core.CacheAdapter$watchClusters$1$1.invoke(CacheAdapter.kt:21) ~[flink-k8s-toolbox.jar:1.3.5-beta]
	at com.nextbreakpoint.flinkoperator.server.operator.core.CacheAdapter$watchClusters$1$1.invoke(CacheAdapter.kt:9) ~[flink-k8s-toolbox.jar:1.3.5-beta]
	at com.nextbreakpoint.flinkoperator.server.operator.core.CacheAdapter.watchResources(CacheAdapter.kt:71) [flink-k8s-toolbox.jar:1.3.5-beta]
	at com.nextbreakpoint.flinkoperator.server.operator.core.CacheAdapter.access$watchResources(CacheAdapter.kt:9) [flink-k8s-toolbox.jar:1.3.5-beta]
	at com.nextbreakpoint.flinkoperator.server.operator.core.CacheAdapter$watchClusters$1.invoke(CacheAdapter.kt:20) [flink-k8s-toolbox.jar:1.3.5-beta]
	at com.nextbreakpoint.flinkoperator.server.operator.core.CacheAdapter$watchClusters$1.invoke(CacheAdapter.kt:9) [flink-k8s-toolbox.jar:1.3.5-beta]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [flink-k8s-toolbox.jar:1.3.5-beta]
2020/11/30 17:48:14.709 +0000 [Thread-8] [CacheAdapter] ERROR An error occurred while watching a resource
io.kubernetes.client.ApiException: Forbidden
```

**Comment by nextbreakpoint** [comment]
Hi rogaha, I guess that some roles or permissions are missing. Did you create the roles using the helm chart? 
helm install flink-k8s-toolbox-roles helm/flink-k8s-toolbox-roles --namespace flink-jobs

**Comment by nextbreakpoint** [comment]
Hi rogaha, do you still have the issue?

**Comment by nextbreakpoint** [comment]
closing the issue for now. please reopen if you need help
